baseURL = "/"
languageCode = "en-us"
title = "Nodeshift from Red Hat"
defaultcontentlanguage = "en"
theme = "hugo-coder"
canonifyurls = true

[params]
    info = "Node.js projects from Red Hat Middleware"
    description = "Node.js projects from Red Hat Middleware"
    keywords = "Red Hat, Node.js"
    avatarurl = "/images/nodeshift_logo_lightbkg.svg"

    favicon_32 = "/images/nodeshift_icon.svg"
    favicon_16 = "/images/nodeshift_icon.svg"

    footercontent = "Copyright Red Hat, Inc."

    hidecredits = true
    hidecopyright = false
    commit = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/nodeshift/"
[[params.social]]
    name = "Jira"
    icon = "fab fa-jira fa-2x"
    weight = 2
    url = "https://issues.jboss.org/projects/NODE/"

# Menu links
[[menu.main]]
    name = "opossum"
    weight = 1
    url  = "https://opossum.nodeshift.dev/"
[[menu.main]]
    name = "nodeshift"
    weight = 2
    url = "http://github.com/nodeshift/nodeshift"